### ISSUE TITLE
 it would be wonderful if we could filter prices for locations within _n_ meters, after providing latitude/longitude

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices#285] opened 2024-05-02 19:19 UTC
@teolemon Not really from the PoC, but it would be wonderful if we could filter prices for locations within _n_ meters, after providing latitude/longitude:
* we could know the prices in shops that are close enough to me (instead of remote cheaper / more expensive locations)
* we could imagine a crazy feature like "this is my shopping cart: tell me which shop in the neighborhood is the cheapest"
* without the lat/lon/meter filter, providing a list of locations (instead of a single) - give me the prices for "my favorite locations"

Besides, the most annoying part is finding the location. Not convinced so far by what I implemented in the PoC or what is implemented in `prices`. Still looking for a "get the shops that match 'monoprix avenue daumesnil paris'" easy method.

cc @raphodn @raphael0202

_Originally posted by @monsieurtanuki in https://github.com/openfoodfacts/smooth-app/issues/5072#issuecomment-1949126838_

**Comment by raphodn** [comment] 2024-05-03 10:26
duplicate of #277

**Closed by raphodn** 2024-05-03 10:26 UTC
Labels: ✨ enhancement, 📍 Location
